"""Regenerate the checked-in Forge effect-API list from a Forge checkout.

The list exists so the test suite needs no JVM and no sibling checkout. That is
worth keeping and is exactly why it drifts: nothing regenerates it when Forge
moves. Run this after a Forge upgrade; the test beside it fails until you do.

    python scripts/regenerate_forge_api_list.py --forge ../forge

Also prints, for every ``ApiType`` member whose own effect class stems to a
different name, ``class-stem -> member``. A hand-maintained mapping keyed by
one of Forge's effect APIs (``EFFECT_API_EVENTS`` in
``src/effects/domain/event_schema.py``) is keyed by the enum member's *name*,
not its effect *class*, and the two used to be assumed identical. They are not
-- ``GainControl (ControlGainEffect.class)`` is a member called ``GainControl``
whose class stems to ``ControlGain`` -- so printing the pairing mechanically is
what makes re-keying such a mapping after an upgrade checkable rather than a
run of hand-typed renames.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

HEADER = '''"""Forge's effect APIs, trigger modes, replacement types and game events.

Generated by ``scripts/regenerate_forge_api_list.py`` from a Forge checkout.
Do not hand-edit: the names are enum members, and a hand-fixed name is how the
list came to say ``OwnershipGain`` where Forge says ``GainOwnership``.
"""

from __future__ import annotations
'''

# Matches an enum constant of the shape ``Name (SomeClass.class)`` -- the shape
# shared by ApiType, TriggerType and ReplacementType alike. Anchored on the
# ``.class`` literal rather than a bare ``(`` after the name, for two reasons
# at once: Forge's own formatting is inconsistent about the space before the
# paren (``FlipCoin(FlipCoinEffect.class)`` has none; most members do, and one
# live TriggerType member -- ``DayTimeChanges`` -- doesn't either), and each
# file's own constructor overload starts with a name directly followed by
# ``(`` too (``ApiType(Class<? extends SpellAbilityEffect> clsEf)``). A regex
# that requires the space silently drops members that lack it, which is the
# same failure mode as the drift this script exists to fix; one that instead
# requires a bare ``(`` silently gains the constructor line. Requiring
# ``.class`` immediately after the parenthesis catches every real member
# regardless of spacing while a parameter-list declaration never satisfies it.
_ENUM_CONSTANT = re.compile(r"^\s+([A-Za-z]+)\s*\(\s*([A-Za-z]+)\.class", re.M)


def enum_members(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    return sorted({member for member, _cls in _ENUM_CONSTANT.findall(text)})


def class_stem_pairs(path: Path) -> dict[str, str]:
    """Each live member's own effect class, ``Effect``-suffix stripped.

    Where several members share a class -- ApiType's three internal ``Charm``
    aliases all name ``CharmEffect``, alongside ``Charm`` itself -- prefer the
    member whose name equals the stem outright over "whichever the enum
    happens to list first". The self-consistent pairing is correct on its own
    terms (a class named ``CharmEffect`` really is ``Charm``'s own class), not
    merely lucky about today's ordering; relying on file order instead would
    make this function's one correctness property a fact about Forge's
    formatting rather than one this function enforces, and a future reorder
    could silently turn the printed rename table into a wrong suggestion
    (``Charm -> CompanionChoose``) for the one artifact meant to be derived
    rather than hand-typed. Falling back to first-seen only when no member
    matches the stem keeps every class resolving to some member.
    """
    by_stem: dict[str, list[str]] = {}
    for member, cls in _ENUM_CONSTANT.findall(path.read_text(encoding="utf-8")):
        by_stem.setdefault(cls.removesuffix("Effect"), []).append(member)
    return {
        stem: stem if stem in members else members[0]
        for stem, members in by_stem.items()
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--forge", type=Path, default=Path("../forge"))
    parser.add_argument(
        "--output", type=Path,
        default=Path("src/effects/domain/forge_effect_apis.py"),
    )
    args = parser.parse_args()
    game = args.forge / "forge-game/src/main/java/forge/game"
    blocks = {
        "EFFECT_APIS": enum_members(game / "ability/ApiType.java"),
        "TRIGGER_TYPES": enum_members(game / "trigger/TriggerType.java"),
        "REPLACEMENT_TYPES": enum_members(game / "replacement/ReplacementType.java"),
        # GameEvent.java is the abstract base every real event extends, not an
        # event of its own -- the only member of this glob without a further
        # suffix, so excluding that one name is exact, not heuristic.
        "GAME_EVENTS": sorted(
            p.stem for p in (game / "event").glob("GameEvent*.java")
            if p.stem != "GameEvent"
        ),
    }
    lines = [HEADER]
    for name, members in blocks.items():
        lines.append(f"{name}: frozenset[str] = frozenset({{")
        lines.extend(f'    "{m}",' for m in members)
        lines.append("})\n\n")
    args.output.write_text("\n".join(lines), encoding="utf-8")
    for name, members in blocks.items():
        print(f"{name}: {len(members)}")

    renames = {
        stem: member
        for stem, member in class_stem_pairs(game / "ability/ApiType.java").items()
        if stem != member
    }
    print(f"\nApiType class-stem -> member, where they differ ({len(renames)}):")
    for stem, member in sorted(renames.items()):
        print(f"  {stem} -> {member}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
